/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as CookIndexRouteImport } from './routes/cook.index'
import { Route as CookSlugRouteImport } from './routes/cook.$slug'
import { Route as RecipeSlugRouteImport } from './routes/recipe.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const CookIndexRoute = CookIndexRouteImport.update({
  id: '/cook/',
  path: '/cook/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookSlugRoute = CookSlugRouteImport.update({
  id: '/cook/$slug',
  path: '/cook/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeSlugRoute = RecipeSlugRouteImport.update({
  id: '/recipe/$slug',
  path: '/recipe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/ingredients': typeof IngredientsRoute
  '/saved': typeof SavedRoute
  '/suggestions': typeof SuggestionsRoute
  '/cook/$slug': typeof CookSlugRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/cook/': typeof CookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/ingredients': typeof IngredientsRoute
  '/saved': typeof SavedRoute
  '/suggestions': typeof SuggestionsRoute
  '/cook/$slug': typeof CookSlugRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/cook': typeof CookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/ingredients': typeof IngredientsRoute
  '/saved': typeof SavedRoute
  '/suggestions': typeof SuggestionsRoute
  '/cook/$slug': typeof CookSlugRoute
  '/recipe/$slug': typeof RecipeSlugRoute
  '/cook/': typeof CookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/ingredients'
    | '/saved'
    | '/suggestions'
    | '/cook/$slug'
    | '/recipe/$slug'
    | '/cook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/ingredients'
    | '/saved'
    | '/suggestions'
    | '/cook/$slug'
    | '/recipe/$slug'
    | '/cook'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/ingredients'
    | '/saved'
    | '/suggestions'
    | '/cook/$slug'
    | '/recipe/$slug'
    | '/cook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  IngredientsRoute: typeof IngredientsRoute
  SavedRoute: typeof SavedRoute
  SuggestionsRoute: typeof SuggestionsRoute
  CookSlugRoute: typeof CookSlugRoute
  RecipeSlugRoute: typeof RecipeSlugRoute
  CookIndexRoute: typeof CookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook/': {
      id: '/cook/'
      path: '/cook'
      fullPath: '/cook/'
      preLoaderRoute: typeof CookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook/$slug': {
      id: '/cook/$slug'
      path: '/cook/$slug'
      fullPath: '/cook/$slug'
      preLoaderRoute: typeof CookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$slug': {
      id: '/recipe/$slug'
      path: '/recipe/$slug'
      fullPath: '/recipe/$slug'
      preLoaderRoute: typeof RecipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  IngredientsRoute: IngredientsRoute,
  SavedRoute: SavedRoute,
  SuggestionsRoute: SuggestionsRoute,
  CookSlugRoute: CookSlugRoute,
  RecipeSlugRoute: RecipeSlugRoute,
  CookIndexRoute: CookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
